package net.jrodolfo.java_evolution.java06.compiler_api;

import static org.assertj.core.api.Assertions.assertThat;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Collections;
import javax.tools.Diagnostic;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

class CompilerApiExamplesTest {

	private final CompilerApiExamples examples = new CompilerApiExamples();

	@Test
	void systemCompilerIsAvailableOnTheProjectJdkBaseline() {
		assertThat(examples.systemCompilerIsAvailable())
				.as("The repository runs on a JDK baseline, so ToolProvider should find a system Java compiler")
				.isTrue();
	}

	@Test
	void compilerApiCompilesRealSourceFilesIntoClassFiles(@TempDir Path workspace) throws Exception {
		Path sourceDirectory = Files.createDirectories(workspace.resolve("src/demo"));
		Path outputDirectory = workspace.resolve("classes");
		Path sourceFile = sourceDirectory.resolve("GeneratedGreeting.java");

		Files.writeString(sourceFile,
				"package demo;\n"
						+ "\n"
						+ "public class GeneratedGreeting {\n"
						+ "\tpublic String message() {\n"
						+ "\t\treturn \"hello from generated source\";\n"
						+ "\t}\n"
						+ "}\n");

		CompilerApiExamples.CompilationResult result = examples.compile(Collections.singletonList(sourceFile.toFile()),
				outputDirectory.toFile());

		assertThat(result.successful())
				.as("JavaCompiler should compile the temporary Java source file without launching javac separately")
				.isTrue();
		assertThat(result.errors())
				.as("A successful compilation should not produce compiler errors")
				.isEmpty();
		assertThat(outputDirectory.resolve("demo/GeneratedGreeting.class"))
				.as("The standard file manager should place generated bytecode in the configured class-output directory")
				.exists();
	}

	@Test
	void compilerApiReportsStructuredDiagnosticsForInvalidSource(@TempDir Path workspace) throws Exception {
		Path sourceDirectory = Files.createDirectories(workspace.resolve("src/demo"));
		Path outputDirectory = workspace.resolve("classes");
		Path sourceFile = sourceDirectory.resolve("Broken.java");

		Files.writeString(sourceFile,
				"package demo;\n"
						+ "\n"
						+ "public class Broken {\n"
						+ "\tpublic void broken() {\n"
						+ "\t\tmissingSymbol();\n"
						+ "\t}\n"
						+ "}\n");

		CompilerApiExamples.CompilationResult result = examples.compile(Collections.singletonList(sourceFile.toFile()),
				outputDirectory.toFile());

		assertThat(result.successful())
				.as("Invalid Java source should make the compilation task report failure")
				.isFalse();
		assertThat(result.errors())
				.as("DiagnosticCollector should expose structured compiler errors instead of only console text")
				.hasSize(1)
				.first()
				.extracting(Diagnostic::getKind)
				.isEqualTo(Diagnostic.Kind.ERROR);
		assertThat(result.errors().get(0).getMessage(null))
				.as("Diagnostics should preserve the compiler's explanation for the learner or tool")
				.contains("missingSymbol");
	}
}
